CREATE TABLE Persons(Id INTEGER PRIMARY KEY, Name TEXT NOT NULL, Age INTEGER NOT NULL);
CREATE TABLE Parameters(Id INTEGER PRIMARY KEY, Name TEXT NOT NULL, Type TEXT NOT NULL);
CREATE TABLE ParameterValues(
	PersonId INTEGER,
	ParameterId INTEGER,
	PRIMARY KEY (PersonId, ParameterId),
	FOREIGN KEY (PersonId) REFERENCES Persons (PersonId) ON DELETE CASCADE ON UPDATE NO ACTION,
	FOREIGN KEY (ParameterId) REFERENCES groups (ParameterId) ON DELETE CASCADE ON UPDATE NO ACTION);